In [1]:
import pandas as pd

In [2]:
df_candidates = pd.read_csv("../production_data/raw_data_dump/candidates.csv")
df_candidates.head(2)

,_id,created_at,updated_at,company_id,job_id,name,email,phone_no,status,type,...,compatibility_analysis.detailed_scoring.overall_potential,ats_analysis.ats_score,ats_analysis.skills_summary.measurable_achievements,ats_analysis.skills_summary.hard_skills,ats_analysis.skills_summary.soft_skills,ats_analysis.skills_summary.skills_efficiency_score,ats_analysis.red_flags,ats_analysis.recommendations,progress.round_1,progress.round_2
0,682207656342bdaa11723988,2025-05-12 14:36:21.192,2025-05-12 14:36:21.192,682200936342bdaa1172397a,6822017e6342bdaa1172397d,Supriya Ricard,supriya+1@klizos.com,NaN,new,general,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,682207f36342bdaa11723989,2025-05-12 14:38:43.661,2025-05-12 14:38:43.661,682200936342bdaa1172397a,6822017e6342bdaa1172397d,Sourav Rooj,Sourav.rooj@klizos.com,NaN,new,general,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_candidates.columns

Index(['_id', 'created_at', 'updated_at', 'company_id', 'job_id', 'name',
       'email', 'phone_no', 'status', 'type', 'secondary_email',
       'primary_phone', 'secondary_phone', 'cv_directory_link', 'unique_id',
       'designation', 'location', 'education', 'work_experience',
       'total_experience', 'technical_skills', 'soft_skills', 'languages',
       'certifications', 'projects', 'batch_id',
       'personal_details.date_of_birth', 'personal_details.age',
       'personal_details.gender', 'social_profiles.github',
       'social_profiles.linkedin', 'social_profiles.twitter',
       'social_profiles.leetcode', 'social_profiles.others', 'metadata.pages',
       'metadata.file_size_kb', 'metadata.file_type', 'metadata.word_count',
       'metadata.personal_pronoun_count', 'metadata.reading_level',
       'metadata.vocabulary_level', 'metadata.frequent_words',
       'compatibility_analysis.overall_score',
       'compatibility_analysis.analysis.strengths',
       'compatibility_analysis.analysis.gaps',
       'compatibility_analysis.analysis.matching_points',
       'compatibility_analysis.analysis.improvement_areas',
       'compatibility_analysis.detailed_scoring.skills_match',
       'compatibility_analysis.detailed_scoring.experience_relevance',
       'compatibility_analysis.detailed_scoring.education_fit',
       'compatibility_analysis.detailed_scoring.overall_potential',
       'ats_analysis.ats_score',
       'ats_analysis.skills_summary.measurable_achievements',
       'ats_analysis.skills_summary.hard_skills',
       'ats_analysis.skills_summary.soft_skills',
       'ats_analysis.skills_summary.skills_efficiency_score',
       'ats_analysis.red_flags', 'ats_analysis.recommendations',
       'progress.round_1', 'progress.round_2'],
      dtype='object')