#### Import required package

In [1]:
import pandas as pd
pd.set_option("display.max_column", None)

#### Read the collection data

In [2]:
df = pd.read_csv("../../../production_data/raw_data_dump/candidates.csv")
df.sample(2)

,_id,created_at,updated_at,company_id,job_id,name,email,phone_no,status,type,progress.round_2.score,progress.round_2.value,secondary_email,primary_phone,secondary_phone,cv_directory_link,unique_id,designation,location,education,work_experience,total_experience,technical_skills,soft_skills,languages,certifications,projects,batch_id,total_experience_months,personal_details.date_of_birth,personal_details.age,personal_details.gender,social_profiles.github,social_profiles.linkedin,social_profiles.twitter,social_profiles.leetcode,social_profiles.others,metadata.pages,metadata.file_size_kb,metadata.file_type,metadata.word_count,metadata.personal_pronoun_count,metadata.reading_level,metadata.vocabulary_level,metadata.frequent_words,compatibility_analysis.overall_score,compatibility_analysis.analysis.strengths,compatibility_analysis.analysis.gaps,compatibility_analysis.analysis.matching_points,compatibility_analysis.analysis.improvement_areas,compatibility_analysis.detailed_scoring.skills_match,compatibility_analysis.detailed_scoring.experience_relevance,compatibility_analysis.detailed_scoring.education_fit,compatibility_analysis.detailed_scoring.overall_potential,ats_analysis.ats_score,ats_analysis.skills_summary.measurable_achievements,ats_analysis.skills_summary.hard_skills,ats_analysis.skills_summary.soft_skills,ats_analysis.skills_summary.skills_efficiency_score,ats_analysis.red_flags,ats_analysis.recommendations,progress.round_1.value,progress.round_1.score,currency,current_location,join_immediately,notice_period,receiving_stipend,relocation_preferred,salary_current,salary_expected_max,salary_expected_min,salary_negotiable,last_contacted,salary_expected,shift_preference,criteria_note,progress.round_1,linkedin_profile
76,6822f74d3d9e6a1581409256,2025-05-13 07:37:25.238,2025-05-13 07:41:45.597,6822e3346342bdaa117239ba,6822eaf56342bdaa117239bd,Van Nhu Hao,vnhuhao.dn201@gmail.com,NaN,New,NaN,NaN,NaN,NaN,0906562893,NaN,CVs/8d178651,8d178651,NaN,"Chinh Gian, Thanh Khe, Da Nang",[{'degree': 'Bachelor’s Degree in Human Resour...,"[{'company_name': 'Var Meta Corp', 'position':...",2 years 8 months,"['Labor Law Compliance', 'Communication & Nego...","['Communication', 'Planning']","[{'name': 'English', 'proficiency': 'Basic'}, ...","[{'name': 'Active Employee of the Year 2024', ...","[{'name': 'Game Journey', 'project_type': 'pro...",b'.\x95\xe2\x8f(W^\xd6\xb7dM\xd3bs\x04\xd2',32.0,NaN,0.0,NaN,NaN,Linkedin,NaN,NaN,[],2.0,111554560.0,PDF,653.0,5.0,15.1,6.11,"['and', 'of', 'with', 'in', '-', 'the', 'for',...",55.0,['Strong communication and negotiation skills'...,['Lack of specified technical skills relevant ...,"['Experience in HR and administration roles', ...","['Gain additional HR certifications', 'Increas...",50.0,40.0,70.0,60.0,65.0,['Successfully recruited 30 employees with an ...,"['Labor Law Compliance', 'Communication & Nego...","['Communication', 'Planning', 'Teamwork']",14.90,['No direct experience or qualifications relat...,['Revise the resume to focus on relevant teach...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
884,685ade9c3cd3e170c81f4355,2025-06-24 17:21:32.710,2025-06-24 17:30:13.785,681c861b1cf44d32fe03095e,685921ddc939b52e8b71ae2d,Deborah E. Gonzalez Roncal,deborah.roncal@gmail.com,NaN,Shortlisted,general,85.0,True,NaN,(52-1) 33 16235323,NaN,CVs/d86368bf-8eff-5957-8e65-ae83c28d3cf2,d86368bf-8eff-5957-8e65-ae83c28d3cf2,NaN,Mexico City,[{'degree': 'Bachelor’s Degree in Teaching Eng...,"[{'company_name': 'Global English', 'position'...",20 years 0 months,"['Computer literacy', 'Ability to integrate te...",['Coaching and coordinating classroom activiti...,"[{'name': 'English', 'proficiency': 'C2'}, {'n...","[{'name': 'TOEFL ITP', 'issuer': '', 'issue_da...",[],b'\x9dx\xb8G$oQ\xfa\xb6Z\xcf\x11@\xa5\xc4%',240.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,[],4.0,697051136.0,PDF,1063.0,30.0,14.6,4.88,"['and', 'english', 'of', 'in', 'a', '*', 'to',...",88.0,['6 years of experience as an Online Business ...,"['No TEFL/TESOL certification mentioned', 'Lim...","['Experience teaching English to adults', 'Pro...","['Obtain TEFL/TESOL certification', 'Gain more...",85.0,90.0,80.0,90.0,75.0,"['Achieved a TOEFL ITP score of 627', 'Success...","['Computer literacy', 'Live interpretation ski...",['Coaching and coordinating classroom activiti...,8.11,['Overuse of personal pronouns (30 instances) ...,['Reduce the resume length to 1-2 pages to imp...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Inspect the shape and columns of the collection

In [3]:
print("shape: ", df.shape)
print("Columns: ", df.columns)

shape:  (983, 79)
Columns:  Index(['_id', 'created_at', 'updated_at', 'company_id', 'job_id', 'name',
       'email', 'phone_no', 'status', 'type', 'progress.round_2.score',
       'progress.round_2.value', 'secondary_email', 'primary_phone',
       'secondary_phone', 'cv_directory_link', 'unique_id', 'designation',
       'location', 'education', 'work_experience', 'total_experience',
       'technical_skills', 'soft_skills', 'languages', 'certifications',
       'projects', 'batch_id', 'total_experience_months',
       'personal_details.date_of_birth', 'personal_details.age',
       'personal_details.gender', 'social_profiles.github',
       'social_profiles.linkedin', 'social_profiles.twitter',
       'social_profiles.leetcode', 'social_profiles.others', 'metadata.pages',
       'metadata.file_size_kb', 'metadata.file_type', 'metadata.word_count',
       'metadata.personal_pronoun_count', 'metadata.reading_level',
       'metadata.vocabulary_level', 'metadata.frequent_words',
       'compatibility_analysis.overall_score',
       'compatibility_analysis.analysis.strengths',
       'compatibility_analysis.analysis.gaps',
       'compatibility_analysis.analysis.matching_points',
       'compatibility_analysis.analysis.improvement_areas',
       'compatibility_analysis.detailed_scoring.skills_match',
       'compatibility_analysis.detailed_scoring.experience_relevance',
       'compatibility_analysis.detailed_scoring.education_fit',
       'compatibility_analysis.detailed_scoring.overall_potential',
       'ats_analysis.ats_score',
       'ats_analysis.skills_summary.measurable_achievements',
       'ats_analysis.skills_summary.hard_skills',
       'ats_analysis.skills_summary.soft_skills',
       'ats_analysis.skills_summary.skills_efficiency_score',
       'ats_analysis.red_flags', 'ats_analysis.recommendations',
       'progress.round_1.value', 'progress.round_1.score', 'currency',
       'current_location', 'join_immediately', 'notice_period',
       'receiving_stipend', 'relocation_preferred', 'salary_current',
       'salary_expected_max', 'salary_expected_min', 'salary_negotiable',
       'last_contacted', 'salary_expected', 'shift_preference',
       'criteria_note', 'progress.round_1', 'linkedin_profile'],
      dtype='object')

#### Inspect the detail info of the documents present in the collection

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 983 entries, 0 to 982
Data columns (total 79 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   _id                                                           983 non-null    object
 1   created_at                                                    983 non-null    object
 2   updated_at                                                    983 non-null    object
 3   company_id                                                    983 non-null    object
 4   job_id                                                        983 non-null    object
 5   name                                                          981 non-null    object
 6   email                                                         983 non-null    object
 7   phone_no                                                      0 non-null      float64
 8   status                                                        983 non-null    object
 9   type                                                          471 non-null    object
 10  progress.round_2.score                                        525 non-null    float64
 11  progress.round_2.value                                        525 non-null    object
 12  secondary_email                                               13 non-null     object
 13  primary_phone                                                 539 non-null    object
 14  secondary_phone                                               37 non-null     object
 15  cv_directory_link                                             580 non-null    object
 16  unique_id                                                     580 non-null    object
 17  designation                                                   462 non-null    object
 18  location                                                      472 non-null    object
 19  education                                                     580 non-null    object
 20  work_experience                                               580 non-null    object
 21  total_experience                                              580 non-null    object
 22  technical_skills                                              580 non-null    object
 23  soft_skills                                                   580 non-null    object
 24  languages                                                     580 non-null    object
 25  certifications                                                580 non-null    object
 26  projects                                                      580 non-null    object
 27  batch_id                                                      580 non-null    object
 28  total_experience_months                                       580 non-null    float64
 29  personal_details.date_of_birth                                140 non-null    object
 30  personal_details.age                                          580 non-null    float64
 31  personal_details.gender                                       53 non-null     object
 32  social_profiles.github                                        64 non-null     object
 33  social_profiles.linkedin                                      231 non-null    object
 34  social_profiles.twitter                                       7 non-null      object
 35  social_profiles.leetcode                                      5 non-null      object
 36  social_profiles.others                                        580 non-null    object
 37  metadata.pages                                                580 non-null    float64
 38  metadata.file_size_kb                                         580 non-null    float64
 39  metadata.file_type                                            580 non-null    object
 40  metadata.word_count                                           580 non-null    float64
 41  metadata.personal_pronoun_count                               580 non-null    float64
 42  metadata.reading_level                                        580 non-null    float64
 43  metadata.vocabulary_level                                     580 non-null    float64
 44  metadata.frequent_words                                       580 non-null    object
 45  compatibility_analysis.overall_score                          580 non-null    float64
 46  compatibility_analysis.analysis.strengths                     580 non-null    object
 47  compatibility_analysis.analysis.gaps                          580 non-null    object
 48  compatibility_analysis.analysis.matching_points               580 non-null    object
 49  compatibility_analysis.analysis.improvement_areas             580 non-null    object
 50  compatibility_analysis.detailed_scoring.skills_match          580 non-null    float64
 51  compatibility_analysis.detailed_scoring.experience_relevance  580 non-null    float64
 52  compatibility_analysis.detailed_scoring.education_fit         580 non-null    float64
 53  compatibility_analysis.detailed_scoring.overall_potential     580 non-null    float64
 54  ats_analysis.ats_score                                        580 non-null    float64
 55  ats_analysis.skills_summary.measurable_achievements           580 non-null    object
 56  ats_analysis.skills_summary.hard_skills                       580 non-null    object
 57  ats_analysis.skills_summary.soft_skills                       580 non-null    object
 58  ats_analysis.skills_summary.skills_efficiency_score           580 non-null    float64
 59  ats_analysis.red_flags                                        580 non-null    object
 60  ats_analysis.recommendations                                  580 non-null    object
 61  progress.round_1.value                                        556 non-null    object
 62  progress.round_1.score                                        0 non-null      float64
 63  currency                                                      3 non-null      object
 64  current_location                                              2 non-null      object
 65  join_immediately                                              1 non-null      object
 66  notice_period                                                 11 non-null     float64
 67  receiving_stipend                                             1 non-null      object
 68  relocation_preferred                                          5 non-null      object
 69  salary_current                                                3 non-null      float64
 70  salary_expected_max                                           14 non-null     float64
 71  salary_expected_min                                           14 non-null     float64
 72  salary_negotiable                                             4 non-null      object
 73  last_contacted                                                0 non-null      float64
 74  salary_expected                                               1 non-null      float64
 75  shift_preference                                              1 non-null      object
 76  criteria_note                                                 18 non-null     object
 77  progress.round_1                                              13 non-null     object
 78  linkedin_profile                                              0 non-null      float64
dtypes: float64(25), object(54)
memory usage: 606.8+ KB

In [6]:
df_klz = df[df['company_id'] == "681c861b1cf44d32fe03095e"]
df_klz.sample(2)

,_id,created_at,updated_at,company_id,job_id,name,email,phone_no,status,type,progress.round_2.score,progress.round_2.value,secondary_email,primary_phone,secondary_phone,cv_directory_link,unique_id,designation,location,education,work_experience,total_experience,technical_skills,soft_skills,languages,certifications,projects,batch_id,total_experience_months,personal_details.date_of_birth,personal_details.age,personal_details.gender,social_profiles.github,social_profiles.linkedin,social_profiles.twitter,social_profiles.leetcode,social_profiles.others,metadata.pages,metadata.file_size_kb,metadata.file_type,metadata.word_count,metadata.personal_pronoun_count,metadata.reading_level,metadata.vocabulary_level,metadata.frequent_words,compatibility_analysis.overall_score,compatibility_analysis.analysis.strengths,compatibility_analysis.analysis.gaps,compatibility_analysis.analysis.matching_points,compatibility_analysis.analysis.improvement_areas,compatibility_analysis.detailed_scoring.skills_match,compatibility_analysis.detailed_scoring.experience_relevance,compatibility_analysis.detailed_scoring.education_fit,compatibility_analysis.detailed_scoring.overall_potential,ats_analysis.ats_score,ats_analysis.skills_summary.measurable_achievements,ats_analysis.skills_summary.hard_skills,ats_analysis.skills_summary.soft_skills,ats_analysis.skills_summary.skills_efficiency_score,ats_analysis.red_flags,ats_analysis.recommendations,progress.round_1.value,progress.round_1.score,currency,current_location,join_immediately,notice_period,receiving_stipend,relocation_preferred,salary_current,salary_expected_max,salary_expected_min,salary_negotiable,last_contacted,salary_expected,shift_preference,criteria_note,progress.round_1,linkedin_profile
807,685146c76f49c875e3fa0539,2025-06-17 10:43:10.779,2025-06-17 10:43:23.960,681c861b1cf44d32fe03095e,6849372ceabd1dae68df08ad,Chandan Sahu,chandansahuands@gmail.com,NaN,Shortlisted,NaN,NaN,NaN,NaN,+91 8382832152,NaN,CVs/81436025-ba47-5b71-b2b4-84dde8e0f0dc,81436025-ba47-5b71-b2b4-84dde8e0f0dc,Node JS Developer | JavaScript Developer,"Bhubaneswar, Odisha","[{'degree': 'Master in Computer Application', ...","[{'company_name': 'Ajatus Software', 'position...",1 year 9 months,"['Node.js', 'Express.js', 'WebSocket', 'MongoD...",[],"[{'name': 'Odia', 'proficiency': 'Native'}, {'...",[],"[{'name': 'Workforce Management System', 'proj...",b'F\x88I:\xcd\xbf_\xd5\x8c\xa1Z\x9e\xcf\xd4\x05B',21.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,[],1.0,186084352.0,PDF,0.0,0.0,0.0,0.0,[],76.5,"['Proficient in Node.js and MongoDB', 'Experie...","['No experience with TypeScript', 'Limited exp...",['1 year 5 months of relevant experience as a ...,"['Gain experience with TypeScript', 'Work on p...",75.0,80.0,70.0,75.0,45.0,[],"['Node.js', 'Express.js', 'WebSocket', 'MongoD...",[],0.0,"['No measurable achievements listed.', 'No sof...",['Add a detailed work experience section with ...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,6826e7d71b85c2b6f71a5c07,2025-05-16 07:23:03.184,2025-05-16 07:23:03.184,681c861b1cf44d32fe03095e,68249d021b85c2b6f71a5bb4,Rahul Kumar,rahul.k+qa@klizos.com,NaN,new,general,45.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN